
// Objective-C API for talking to the following Go packages
//
//	ebiten-example/gamemobile
//	github.com/hajimehoshi/ebiten/mobile/ebitenmobileview
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mygame_FRAMEWORK_H__
#define __Mygame_FRAMEWORK_H__

#include "Mygame.objc.h"
#include "Ebitenmobileview.objc.h"
#include "Universe.objc.h"

#endif
