// Objective-C API for talking to ebiten-example/gamemobile Go package.
//   gobind -lang=objc ebiten-example/gamemobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mygame_H__
#define __Mygame_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void MygameInitGame(long screenWidth, long screenHeight);

#endif
