// Objective-C API for talking to ebiten-example/mobile Go package.
//   gobind -lang=objc ebiten-example/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void MobileInitGame(long screenWidth, long screenHeight);

#endif
